# Generated by Django 3.1 on 2020-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='information',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
